--DATA MANIPULATION TABLE DML
--INSERT STATEMENT SYNTAX


INSERT INTO emp(EMP_ID,SALARY,EMAIL,DEPARTMENT_ID,NAME,DEPARTMENT_NAME)
VALUES (6,5000,'rakib@gmai.com',13,'rakib','DDD');

select*
from emp;

INSERT INTO emp VALUES (7,'sathe',58000,'sathe@gmai.com',14,'JEE');
COMMIT;